name: Mirror to Repositories

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_PAT}@gitlab.com/maximmig/toolbox-browser-extension-testing.git
          git push gitlab --all
          git push gitlab --tags

      - name: Push to Gitee
        env:
          GITEE_PAT: ${{ secrets.GITEE_PAT }}
        run: |
          git remote add gitee https://oauth2:${GITEE_PAT}@gitee.com/maximmig/toolbox-browser-extension-testing.git
          git push gitee --all
          git push gitee --tags