name: Mirror to Repositories

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_PAT}@gitlab.com/maximmig/toolbox-browser-extension-testing.git
          git push gitlab --all
          git push gitlab --tags

      - name: Push to Gitee
        env:
          GITEE_PAT: ${{ secrets.GITEE_PAT }}
        run: |
          git remote add gitee https://oauth2:${GITEE_PAT}@gitee.com/maximmig/toolbox-browser-extension-testing.git
          git push gitee --all --force
          git push gitee --tags --force

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BITBUCKET_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 bitbucket.org >> ~/.ssh/known_hosts

      - name: Push to Bitbucket
        env:
          GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_ed25519'
        run: |
          git remote add bitbucket git@bitbucket.org:maximmig-tbx/toolbox-browser-extension-testing.git
          git push -u bitbucket main --force